=pod

=head1 DESCRIPTION

=head2 Booleans

  TRUE
  FALSE

=head2 Attributes

Modules defaults to C<< is => ro >>

  # init_arg => "foo", accessor => "foo"
  has foo ( is => rw );

  # init_arg => "foo", reader => "foo"
  has foo ( is => ro );

  # init_arg => "foo", reader => "foo", writer => "_set_foo"
  has foo ( is => rwp );
  
  # init_arg => "foo",
  has foo ( is => bare );
  
  # no init_arg or accessor methods created!
  has foo ( is => private );
  
  # 'param' synonym for has but defaults to 'required => 1'
  param foo ( type => Str );
  
  # 'field' synonym for has but defaults to 'init_arg => undef'
  field foo ( builder => 1 );
  
  # 'has name!' is a shorthand for the longer
  has name ( required => 1 );
  
  # has name ( is => rw, default => "Anonymous" ) can be written as
  has name ( is => rw ) = "Anonymous";

=head2 Attribute privacy

  rw
  rwp
  ro
  lazy
  bare
  private

=cut
